server:
  port: 4020
  undertow:
    url-charset: UTF-8
    threads:
      io: 16
      worker: 256
    buffer-size: 1024
    direct-buffers: true
    max-http-post-size: 20MB


spring:
  application:
    name: thumb-backend
  profiles:
    active: de
  cache:
    type: redis
    redis:
      key-prefix: ${spring.application.name}
  data:
    redis:
      lettuce:
        pool:
          enabled: true
          max-active: 12
          max-idle: 8
          min-idle: 1
          max-wait: 10000
  datasource:
    hikari:
      minimum-idle: 8
      maximum-pool-size: 12
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
      pool-name: ${spring.application.name}

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.example.thumb.**.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    db-config:
      id-type: input
      insert-strategy: not_null
      update-strategy: always
      capital-mode: true
      logic-delete-field: delFalg
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  file:
    path: /data/logs/${server.port}-${spring.application.name}
  level:
    root: error
    com.example.thumb: info